# Generated by Django 2.0.2 on 2022-01-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20210130_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='partner_imgs'),
        ),
    ]
