# Generated by Django 2.0.2 on 2018-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('positionMan', models.IntegerField(blank=True, null=True)),
                ('positionYouth', models.IntegerField(blank=True, null=True)),
                ('trainer', models.BooleanField()),
                ('ansprechpartner', models.BooleanField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='player_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('league', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='team_imgs')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
