# Generated by Django 2.0.2 on 2018-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='positionMan',
        ),
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='player_imgs'),
        ),
        migrations.AddField(
            model_name='player',
            name='positionYouth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.CharField(default=1.0, max_length=200),
            preserve_default=False,
        ),
    ]
