# Generated by Django 2.0.2 on 2018-03-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180311_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ansprechpartner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='trainer',
            field=models.BooleanField(default=False),
        ),
    ]
