# Generated by Django 2.0.2 on 2018-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180303_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='positionMan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='positionYouth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
