# Generated by Django 2.0 on 2018-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20180313_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ManyToManyField(blank=True, to='teams.Role'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, to='teams.Team'),
        ),
    ]
