# Generated by Django 2.0 on 2018-03-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20180313_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='webtt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
