# Generated by Django 2.0 on 2018-03-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_webtt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='webtt',
            new_name='webttFileName',
        ),
    ]
