# Generated by Django 2.0 on 2018-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20180321_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='webttFileName',
            field=models.CharField(default='1.0', max_length=200),
            preserve_default=False,
        ),
    ]
