# Generated by Django 2.0 on 2018-03-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20180321_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='webttFileName',
        ),
    ]
