# Generated by Django 2.0 on 2018-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_remove_team_webttfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='webttFileName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
