# Generated by Django 2.0.2 on 2018-07-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_webttfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teilnehmer',
            field=models.CharField(default='6', max_length=200),
            preserve_default=False,
        ),
    ]
