# Generated by Django 2.0.2 on 2022-01-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(max_length=200)),
                ('guestScore', models.IntegerField(blank=True, null=True)),
                ('homeName', models.CharField(max_length=200)),
                ('homeScore', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
