# Generated by Django 2.0.2 on 2022-01-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livescore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livescore',
            name='scoreboard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
